# 应用配置
spring.application.name=ai_consult_backend

# 文件上传配置
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Dify API 配置
dify.api.url=http://localhost/v1
# Workflow API Key（用于工作流执行）
dify.workflow.api.key=app-5ugJHDB5HjmtHhJk6N7g049R
# 对话流 API Key（用于聊天）
dify.chatflow.api.key=app-5ugJHDB5HjmtHhJk6N7g049R
# 知识库 API Key（用于文档上传）
dify.dataset.api.key=dataset-bS4sewA3hsYKdMeVWZmCmesI
# dify.knowledge.base.id=c26b5df9-bf76-4551-bcc7-131b3f4273b3
dify.knowledge.base.id=cba4a6f1-47d6-4f73-838b-86bccb233097
dify.workflow.id=8b858a73-c53e-4779-a1ea-ab0d79f3b590
# H2 数据库配置
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
